import { PostData } from '@/components/posts/PostCard'

export const mockPosts: PostData[] = [
  {
    id: '1',
    authorName: 'PortalAdmin',
    authorHandle: '@portal_admin',
    authorInitials: 'PO',
    authorBg: '#1a0030',
    authorColor: '#e879f9',
    role: 'superuser',
    time: 'Ha 2 horas',
    text: 'Bem-vindos ao PORTAL — a rede social criada para otakus apaixonados! Estamos agora em beta e queremos ouvir o vosso feedback. Partilhem as vossas opinioes e ajudem-nos a construir a melhor comunidade de anime e manga da lingua portuguesa.',
    tags: ['Anuncio', 'Beta', 'Portal'],
    isPinned: true,
    likes: 2400,
    comments: 318,
    shares: 145,
    isLiked: true,
  },
  {
    id: '2',
    authorName: 'AkiraFan99',
    authorHandle: '@akirafan99',
    authorInitials: 'AK',
    authorBg: '#0a2015',
    authorColor: '#5cfcb4',
    time: 'Ha 45 minutos',
    text: 'Finalmente acabei de ver Frieren: Beyond Journey\'s End e estou completamente destruido emocionalmente. Este anime e uma obra-prima absoluta. A forma como trata o tempo e a solitude e algo que nunca vi em mais nenhum anime.',
    tags: ['Frieren', 'Fantasy', 'Recomendacao'],
    imageCount: 1,
    likes: 847,
    comments: 124,
    shares: 56,
  },
  {
    id: '3',
    authorName: 'YukiSenpai',
    authorHandle: '@yukisenpai',
    authorInitials: 'YS',
    authorBg: '#1a1000',
    authorColor: '#fcb45c',
    role: 'mod',
    time: 'Ha 2 horas',
    text: 'Acabei o episodio 24 de Demon Slayer — Infinity Castle Arc. Precisei de parar a meio para respirar. A animacao do Ufotable neste episodio e outro nivel completamente.',
    hasSpoiler: true,
    spoilerText: 'Hashira Giyu e Tanjiro combinam os seus estilos de respiracao numa batalha final epica. A cena dos 10 minutos sem cortes e simplesmente absurda.',
    tags: ['DemonSlayer', 'Ufotable', 'Spoiler'],
    likes: 1200,
    comments: 287,
    shares: 93,
    isLiked: true,
  },
  {
    id: '4',
    authorName: 'SakuraHime',
    authorHandle: '@sakurahime',
    authorInitials: 'SH',
    authorBg: '#1a0010',
    authorColor: '#fc5c7d',
    time: 'Ha 4 horas',
    category: 'Cosplay',
    text: 'O meu cosplay da Nezuko ficou finalmente pronto! Levei 3 semanas a fazer o kimono a mao. Qual e a vossa opiniao?',
    imageCount: 7,
    likes: 523,
    comments: 98,
    shares: 41,
  },
  {
    id: '5',
    authorName: 'NaruZuki',
    authorHandle: '@naruzuki',
    authorInitials: 'NZ',
    authorBg: '#0a0a2a',
    authorColor: '#7c5cfc',
    time: 'Ha 5 horas',
    text: 'Acabei de ler o capitulo mais recente de One Piece. Oda-sensei continua a surpreender depois de mais de 25 anos. A construcao do mundo neste arco e absolutamente genial.',
    tags: ['OnePiece', 'Manga', 'Oda'],
    likes: 312,
    comments: 67,
    shares: 28,
  },
]

export const mockTrending = [
  { rank: '01', tag: 'DemonSlayer',     count: '4.2k publicacoes' },
  { rank: '02', tag: 'Frieren',         count: '3.8k publicacoes' },
  { rank: '03', tag: 'JujutsuKaisen',   count: '2.9k publicacoes' },
  { rank: '04', tag: 'AnimeSpring2026', count: '2.1k publicacoes' },
  { rank: '05', tag: 'Cosplay',         count: '1.7k publicacoes' },
]

export const mockSuggestions = [
  { name: 'OtakuRei',   handle: '@otakulei',  followers: '2.4k', initials: 'OR', bg: '#1a0030', color: '#e879f9' },
  { name: 'MangaKaNo',  handle: '@mangakano', followers: '1.8k', initials: 'MN', bg: '#0a2015', color: '#5cfcb4' },
  { name: 'RyuKen',     handle: '@ryuken',    followers: '967',  initials: 'RK', bg: '#1a0800', color: '#fc8c5c' },
  { name: 'NaruZuki',   handle: '@naruzuki',  followers: '743',  initials: 'NZ', bg: '#0a0a2a', color: '#7c5cfc' },
]

export const mockEvents = [
  {
    date: '14 Abr · Online',
    dateColor: 'var(--accent2)',
    title: 'Viewing Party — Solo Leveling S2',
    interested: '128 interessados',
  },
  {
    date: '20 Abr · Lisboa',
    dateColor: 'var(--pink)',
    title: 'Lisboa Anime Fest 2026',
    interested: '342 interessados',
  },
]
